# -*- coding: utf-8 -*-
"""calculator_v2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A7Q3o1YjV6zI9i-qTSDqbxpXopH-4Duq
"""

print("calculadora")
num1 = int(input("ingrese un numero: "))
num2 = int(input("ingrese otro numero"))
num3 = int(input("ingrese otro numero mas"))
while True:
  print("menu de opciones")
  print("1 sumar")
  print("2 restar")
  print("3 dividir")
  print("4 multiplicar")
  opc= int(input("ingrese una opcion"))
  if opc ==1:
    print("la suma es: ", num1 + num2 + num3)
    break
  elif opc == 2:
    print("la resta es: ", num1 - num2 - num3)
    break
  elif opc == 3:
    print("la divicion es: ", num1 / num2 / num3)
  elif opc == 4:
     print("la multiplicacion es: ", num1 * num2 * num3)